### ISSUE TITLE
Replacement for SPStackedNav?

### ISSUE THREAD

**Issue by testarut** [spotify/SPStackedNav#6]
Will you release a replacement library for SPStackedNav now that it's deprecated? Are you guys using another version of SPStackedNav internally at Spotify?

**Comment by marmelroy** [comment]
Hey @testarut, thank you for your question. 

There's no current plan for a SPStackedNav replacement and we no longer use the stacked navigation concept in our iPad client. It was that plus the fact that this project was not widely used or well maintained that led to the decision to deprecate it. 

Am not aware of great and well maintained open source alternatives.
